### ISSUE TITLE
does not compile with nim 0.20.2

### ISSUE THREAD

**Issue by RokkuCode** [adelq/ulid#2]
I generated the same example program  as served in the readme

```
import ulid

ulid()
```

Error:
```/home/user/.nimble/pkgs/random-0.5.3/random/private/random_real.nim(53, 50) Error: cannot attach a custom pragma to 'random_real_64'```

Version
```
Nim Compiler Version 0.20.2 [Linux: amd64]
Compiled at 2019-07-17
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 88a0edba4b1a3d535b54336fd589746add54e937
active boot switches: -d:release
```

**Comment by adelq** [comment]
This should be fixed now by #1, do you mind trying out version 0.2.1?
