### ISSUE TITLE
random alphabet selection index error

### ISSUE THREAD

**Issue by donpdonp** [adelq/ulid#3]
Just hit this error with nim 1.2 and ulid 0.2.1
```
isMainModule: IndexError : index 32 not in 0 .. 31
/home/donp/.nimble/pkgs/ulid-0.2.1/ulid.nim(45) ulid
/home/donp/.nimble/pkgs/ulid-0.2.1/ulid.nim(39) encode_random
```
lines 38&39:
```nim
   rand = int(randFloat() * alphabet_size)
   result = alphabet[rand] & result
```
if randFloat() is 0-0.9999, then I believe line 38 should be `* (alphabet_size-1)` to get a random index into the array.

**Comment by adelq** [comment]
Hi there,

I just pushed out a commit (fddb400e8f6c006badd8e2956f40490aa9ffb4db) that should fix this issue by rewriting the random indexing completely. I haven't encountered indexing issues myself myself, and experimentally 0-0.9999... with the `int` wrapper should stay within 0-31, but there were multiple methods of generating random data in ulid 0.2.1 so it's possible it slipped through the cracks.

Thanks for the heads up!
